---
title: "Fake data generator"
output: html_notebook
---

```{r}
library(rstan)
```



```{r}
set.seed(1)
T = 100
x = seq(1, T)
mu = exp(2 + cumsum(rnorm(T, 0, 0.05)))
phi = exp(cumsum(rnorm(T, 0, 0.15)))
```


```{r}
qplot(x, mu)
```

```{r}
qplot(x, phi)
```

```{r}
obs_each_day = rpois(T, 10)
x_obs = rep(1:T, obs_each_day)
X = model.matrix( ~ as.factor(x_obs) - 1)
N = length(x_obs)
```


```{stan output.var=SimuNegBin}
data {
  int<lower=1> T;
  int<lower=1> N;
  matrix[N, T] X;
  vector[T] mu;
  vector[T] phi;
}

transformed data {
  vector[N] mu_pred = X * mu;
  vector[N] phi_pred = X * phi;
}

parameters {
}

transformed parameters {
}

model {
}

generated quantities {
  int y[N] = neg_binomial_2_rng(mu_pred, phi_pred);
}
```

```{r}
data_in = list(
  mu = mu,
  phi = phi,
  T = T,
  N = N,
  X = X
)
```


```{r}
simu = rstan::sampling(
  object = SimuNegBin,
  data = data_in,
  algorithm = 'Fixed_param',
  chains = 1,
  warmup = 0,
  seed = 1)
```

```{r}
samples = rstan::extract(simu)
```

```{r}
y_obs = samples$y[1,]
qplot(x_obs, y_obs, alpha = I(0.2))
```


```{r}
simulated_data = data.frame(x_obs, y_obs)
```

```{r}
write.csv(simulated_data, file = 'Outputs/SimulatedNegBinData.csv')
```

